package com.kabadiwalaconnect.navigation

object Routes {
    const val SPLASH = "splash"
    const val ONBOARDING = "onboarding"
    const val LOGIN = "login"
    const val REGISTER = "register"
    const val HOME = "home"
    const val PICKUP = "pickup"
    const val PICKUP_CONFIRMATION = "pickup-confirmation/{lotId}"
    const val TRACKING = "tracking"
    const val TRACKING_WITH_LOT = "tracking/{lotId}"
    const val HISTORY = "history"
    const val NEARBY = "nearby"
    const val PROFILE = "profile"
    const val SETTINGS = "settings"
    const val COLLECTOR_DASHBOARD = "collector-dashboard"
    const val COLLECTOR_REQUESTS = "collector-requests"
    const val COLLECTOR_ACTIVE_PICKUP = "collector-active-pickup"
    const val COLLECTOR_ACTIVE_PICKUP_WITH_LOT = "collector-active-pickup/{lotId}"
    const val COLLECTOR_HANDOVER = "collector-handover/{lotId}"
    const val COLLECTOR_EARNINGS = "collector-earnings"
    const val COLLECTOR_HISTORY = "collector-history"
    const val COLLECTOR_PROFILE = "collector-profile"
    const val RECYCLER_DASHBOARD = "recycler-dashboard"
    const val RECYCLER_AVAILABLE_LOTS = "recycler-available-lots"
    const val RECYCLER_INCOMING_LOTS = "recycler-incoming-lots"
    const val RECYCLER_LOT_DETAILS = "recycler-lot-details/{lotId}"
    const val RECYCLER_RECYCLING = "recycler-recycling/{lotId}"
    const val RECYCLER_PAYMENTS = "recycler-payments"
    const val RECYCLER_HISTORY = "recycler-history"
    const val RECYCLER_PROFILE = "recycler-profile"

    fun pickupConfirmation(lotId: String): String = "pickup-confirmation/$lotId"
    fun tracking(lotId: String): String = "tracking/$lotId"
    fun collectorActivePickup(lotId: String): String = "collector-active-pickup/$lotId"
    fun collectorHandover(lotId: String): String = "collector-handover/$lotId"
    fun recyclerLotDetails(lotId: String): String = "recycler-lot-details/$lotId"
    fun recyclerRecycling(lotId: String): String = "recycler-recycling/$lotId"
}
